# This workflow is based on the old travis-ci configuration and built from a github actions workflow template.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Docs Build

on:
  push:
    branches: [ rhewett-patch-1 ]
  pull_request:
    branches: [ rhewett-patch-1 ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Pre-installation
      run: |
        python --version
        uname -a
    - name: Install installer dependencies
      run: |
        python -mpip install --progress-bar=off tox -rci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
    - name: Build docs
      run: |
        tox -v -e docs
        
