# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ rhewett-patch-1 ]
  pull_request:
    branches: [ rhewett-patch-1 ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6']
        mpi: ['mpich']
        include:
          - python-version: '3.6'
            toxenv: py36

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Before installation
      run: |
        python --version
        uname -a
        lsb_release -a || true
        bash ci/travis-ci/install-mpi.sh ${{ matrix.mpi }}
        if [[ ${{ matrix.mpi }} == "mpich"   ]]; then mpichversion; fi
    - name: Installation
      run: |
        python -mpip install --progress-bar=off tox -rci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
    - name: Tests
      run: |
        tox -e py36
